"""
Theme Configuration v3.0 - "Clean & Luminous" Design System
============================================================

Design Philosophy:
- Light, Clean, High-Trust aesthetics (Stripe/Apple style)
- Lots of whitespace, subtle shadows, crisp typography
- NO dark mode backgrounds - always light and inviting
- Depth through shadows, not colored blocks

Three Core Archetypes:
A) Medical/Corporate (Trust) - Blue tones, clinical, serious
B) Retail/Food (Vibrant) - Warm tones, energetic, inviting  
C) Industrial/Services (Solid) - Strong, durable, reliable
"""

from typing import Dict, Any


# =============================================================================
# 🎨 THEME DEFINITIONS - CLEAN & LUMINOUS SYSTEM
# =============================================================================

THEMES: Dict[str, Dict[str, Any]] = {
    
    # =========================================================================
    # THEME A: MEDICAL / CORPORATE (Trust)
    # For: Dentists, Clinics, Doctors, Lawyers, Accountants, Corporate
    # Vibe: Professional, clinical, serious, trustworthy
    # =========================================================================
    
    "medical": {
        "name": "Medical Trust",
        "mode": "light",
        # Backgrounds
        "bg_primary": "bg-slate-50",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-slate-900/90 via-slate-900/70 to-slate-900/40",
        # Text
        "text_primary": "text-slate-800",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        # Brand Colors
        "primary": "blue-600",
        "primary_bg": "bg-blue-600",
        "primary_text": "text-blue-600",
        "primary_hover": "hover:bg-blue-700",
        "primary_light": "bg-blue-50",
        "primary_light_text": "text-blue-700",
        # Accent
        "accent": "sky-500",
        "accent_bg": "bg-sky-500",
        "accent_text": "text-sky-500",
        "accent_light": "bg-sky-50",
        # UI Elements
        "border": "border-gray-200",
        "border_hover": "hover:border-blue-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-slate-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-slate-300/50",
        # Buttons
        "btn_primary": "bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg shadow-blue-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-blue-500 hover:text-blue-600",
        # Cards
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        # Navbar
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        # Icon backgrounds
        "icon_bg": "bg-blue-100",
        "icon_text": "text-blue-600",
        # Rating
        "star_color": "text-amber-400",
        # Footer
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "dentista": {
        "name": "Dental Clean",
        "mode": "light",
        "bg_primary": "bg-slate-50",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-teal-900/90 via-teal-900/70 to-teal-800/40",
        "text_primary": "text-slate-800",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "teal-600",
        "primary_bg": "bg-teal-600",
        "primary_text": "text-teal-600",
        "primary_hover": "hover:bg-teal-700",
        "primary_light": "bg-teal-50",
        "primary_light_text": "text-teal-700",
        "accent": "cyan-500",
        "accent_bg": "bg-cyan-500",
        "accent_text": "text-cyan-500",
        "accent_light": "bg-cyan-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-teal-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-slate-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-teal-200/30",
        "btn_primary": "bg-gradient-to-r from-teal-600 to-teal-700 hover:from-teal-700 hover:to-teal-800 text-white shadow-lg shadow-teal-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-teal-500 hover:text-teal-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-teal-100",
        "icon_text": "text-teal-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "odontología": {
        "name": "Odontología Premium",
        "mode": "light",
        "bg_primary": "bg-gray-50",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-cyan-900/90 via-cyan-900/70 to-cyan-800/40",
        "text_primary": "text-slate-800",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "cyan-600",
        "primary_bg": "bg-cyan-600",
        "primary_text": "text-cyan-600",
        "primary_hover": "hover:bg-cyan-700",
        "primary_light": "bg-cyan-50",
        "primary_light_text": "text-cyan-700",
        "accent": "teal-500",
        "accent_bg": "bg-teal-500",
        "accent_text": "text-teal-500",
        "accent_light": "bg-teal-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-cyan-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-slate-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-cyan-200/30",
        "btn_primary": "bg-gradient-to-r from-cyan-600 to-cyan-700 hover:from-cyan-700 hover:to-cyan-800 text-white shadow-lg shadow-cyan-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-cyan-500 hover:text-cyan-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-cyan-100",
        "icon_text": "text-cyan-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "clínica": {
        "name": "Clinical Trust",
        "mode": "light",
        "bg_primary": "bg-slate-50",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-blue-900/90 via-blue-900/70 to-blue-800/40",
        "text_primary": "text-slate-800",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "blue-600",
        "primary_bg": "bg-blue-600",
        "primary_text": "text-blue-600",
        "primary_hover": "hover:bg-blue-700",
        "primary_light": "bg-blue-50",
        "primary_light_text": "text-blue-700",
        "accent": "sky-500",
        "accent_bg": "bg-sky-500",
        "accent_text": "text-sky-500",
        "accent_light": "bg-sky-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-blue-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-slate-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-blue-200/30",
        "btn_primary": "bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg shadow-blue-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-blue-500 hover:text-blue-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-blue-100",
        "icon_text": "text-blue-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "veterinaria": {
        "name": "Pet Care Fresh",
        "mode": "light",
        "bg_primary": "bg-emerald-50/30",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-emerald-900/90 via-emerald-900/70 to-emerald-800/40",
        "text_primary": "text-slate-800",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "emerald-600",
        "primary_bg": "bg-emerald-600",
        "primary_text": "text-emerald-600",
        "primary_hover": "hover:bg-emerald-700",
        "primary_light": "bg-emerald-50",
        "primary_light_text": "text-emerald-700",
        "accent": "lime-500",
        "accent_bg": "bg-lime-500",
        "accent_text": "text-lime-600",
        "accent_light": "bg-lime-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-emerald-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-slate-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-emerald-200/30",
        "btn_primary": "bg-gradient-to-r from-emerald-600 to-emerald-700 hover:from-emerald-700 hover:to-emerald-800 text-white shadow-lg shadow-emerald-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-emerald-500 hover:text-emerald-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-emerald-100",
        "icon_text": "text-emerald-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    # =========================================================================
    # THEME B: RETAIL / FOOD (Vibrant)
    # For: Restaurants, Cafés, Bakeries, Retail stores, Beauty salons
    # Vibe: Energetic, clean, inviting, appetizing
    # =========================================================================
    
    "retail": {
        "name": "Retail Vibrant",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-gray-50",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-orange-900/90 via-amber-900/70 to-orange-800/40",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "orange-500",
        "primary_bg": "bg-orange-500",
        "primary_text": "text-orange-500",
        "primary_hover": "hover:bg-orange-600",
        "primary_light": "bg-orange-50",
        "primary_light_text": "text-orange-600",
        "accent": "yellow-400",
        "accent_bg": "bg-yellow-400",
        "accent_text": "text-yellow-500",
        "accent_light": "bg-yellow-50",
        "border": "border-gray-100",
        "border_hover": "hover:border-orange-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-orange-200/30",
        "btn_primary": "bg-gradient-to-r from-orange-500 to-orange-600 hover:from-orange-600 hover:to-orange-700 text-white shadow-lg shadow-orange-500/30",
        "btn_secondary": "bg-white text-gray-700 border-2 border-gray-200 hover:border-orange-500 hover:text-orange-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-orange-100",
        "icon_text": "text-orange-500",
        "star_color": "text-amber-400",
        "footer_bg": "bg-gray-900",
        "footer_text": "text-gray-300",
    },
    
    "restaurante": {
        "name": "Restaurant Elegance",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-amber-50/30",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-amber-950/90 via-amber-900/75 to-orange-900/50",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "amber-600",
        "primary_bg": "bg-amber-600",
        "primary_text": "text-amber-600",
        "primary_hover": "hover:bg-amber-700",
        "primary_light": "bg-amber-50",
        "primary_light_text": "text-amber-700",
        "accent": "orange-500",
        "accent_bg": "bg-orange-500",
        "accent_text": "text-orange-500",
        "accent_light": "bg-orange-50",
        "border": "border-gray-100",
        "border_hover": "hover:border-amber-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-amber-200/30",
        "btn_primary": "bg-gradient-to-r from-amber-600 to-amber-700 hover:from-amber-700 hover:to-amber-800 text-white shadow-lg shadow-amber-500/30",
        "btn_secondary": "bg-white text-gray-700 border-2 border-gray-200 hover:border-amber-500 hover:text-amber-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-amber-100",
        "icon_text": "text-amber-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-gray-900",
        "footer_text": "text-gray-300",
    },
    
    "parrilla": {
        "name": "Grill & Fire",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-orange-50/30",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-red-950/90 via-orange-900/80 to-amber-900/50",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "orange-600",
        "primary_bg": "bg-orange-600",
        "primary_text": "text-orange-600",
        "primary_hover": "hover:bg-orange-700",
        "primary_light": "bg-orange-50",
        "primary_light_text": "text-orange-700",
        "accent": "red-500",
        "accent_bg": "bg-red-500",
        "accent_text": "text-red-500",
        "accent_light": "bg-red-50",
        "border": "border-gray-100",
        "border_hover": "hover:border-orange-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-orange-200/30",
        "btn_primary": "bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-700 hover:to-red-700 text-white shadow-lg shadow-orange-500/30",
        "btn_secondary": "bg-white text-gray-700 border-2 border-gray-200 hover:border-orange-500 hover:text-orange-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-orange-100",
        "icon_text": "text-orange-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-gray-900",
        "footer_text": "text-gray-300",
    },
    
    "café": {
        "name": "Coffee House",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-amber-50/50",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-amber-950/90 via-amber-900/70 to-yellow-900/40",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "amber-700",
        "primary_bg": "bg-amber-700",
        "primary_text": "text-amber-700",
        "primary_hover": "hover:bg-amber-800",
        "primary_light": "bg-amber-50",
        "primary_light_text": "text-amber-800",
        "accent": "yellow-500",
        "accent_bg": "bg-yellow-500",
        "accent_text": "text-yellow-600",
        "accent_light": "bg-yellow-50",
        "border": "border-gray-100",
        "border_hover": "hover:border-amber-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-amber-200/30",
        "btn_primary": "bg-gradient-to-r from-amber-700 to-amber-800 hover:from-amber-800 hover:to-amber-900 text-white shadow-lg shadow-amber-500/30",
        "btn_secondary": "bg-white text-gray-700 border-2 border-gray-200 hover:border-amber-500 hover:text-amber-700",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-amber-100",
        "icon_text": "text-amber-700",
        "star_color": "text-amber-400",
        "footer_bg": "bg-gray-900",
        "footer_text": "text-gray-300",
    },
    
    "cafetería": {
        "name": "Cafetería Warm",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-orange-50/30",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-amber-950/90 via-orange-900/70 to-amber-800/40",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "amber-600",
        "primary_bg": "bg-amber-600",
        "primary_text": "text-amber-600",
        "primary_hover": "hover:bg-amber-700",
        "primary_light": "bg-amber-50",
        "primary_light_text": "text-amber-700",
        "accent": "orange-400",
        "accent_bg": "bg-orange-400",
        "accent_text": "text-orange-500",
        "accent_light": "bg-orange-50",
        "border": "border-gray-100",
        "border_hover": "hover:border-amber-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-amber-200/30",
        "btn_primary": "bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-700 hover:to-orange-700 text-white shadow-lg shadow-amber-500/30",
        "btn_secondary": "bg-white text-gray-700 border-2 border-gray-200 hover:border-amber-500 hover:text-amber-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-amber-100",
        "icon_text": "text-amber-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-gray-900",
        "footer_text": "text-gray-300",
    },
    
    "panadería": {
        "name": "Bakery Fresh",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-amber-50/40",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-amber-900/90 via-yellow-900/70 to-orange-800/40",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "amber-600",
        "primary_bg": "bg-amber-600",
        "primary_text": "text-amber-600",
        "primary_hover": "hover:bg-amber-700",
        "primary_light": "bg-amber-50",
        "primary_light_text": "text-amber-700",
        "accent": "yellow-500",
        "accent_bg": "bg-yellow-500",
        "accent_text": "text-yellow-600",
        "accent_light": "bg-yellow-50",
        "border": "border-gray-100",
        "border_hover": "hover:border-amber-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-amber-200/30",
        "btn_primary": "bg-gradient-to-r from-amber-600 to-yellow-600 hover:from-amber-700 hover:to-yellow-700 text-white shadow-lg shadow-amber-500/30",
        "btn_secondary": "bg-white text-gray-700 border-2 border-gray-200 hover:border-amber-500 hover:text-amber-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-amber-100",
        "icon_text": "text-amber-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-gray-900",
        "footer_text": "text-gray-300",
    },
    
    "peluquería": {
        "name": "Beauty Luxe",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-rose-50/30",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-rose-950/90 via-pink-900/70 to-rose-800/40",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "rose-500",
        "primary_bg": "bg-rose-500",
        "primary_text": "text-rose-500",
        "primary_hover": "hover:bg-rose-600",
        "primary_light": "bg-rose-50",
        "primary_light_text": "text-rose-600",
        "accent": "pink-400",
        "accent_bg": "bg-pink-400",
        "accent_text": "text-pink-500",
        "accent_light": "bg-pink-50",
        "border": "border-gray-100",
        "border_hover": "hover:border-rose-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-rose-200/30",
        "btn_primary": "bg-gradient-to-r from-rose-500 to-pink-500 hover:from-rose-600 hover:to-pink-600 text-white shadow-lg shadow-rose-500/30",
        "btn_secondary": "bg-white text-gray-700 border-2 border-gray-200 hover:border-rose-400 hover:text-rose-500",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-rose-100",
        "icon_text": "text-rose-500",
        "star_color": "text-amber-400",
        "footer_bg": "bg-gray-900",
        "footer_text": "text-gray-300",
    },
    
    "barbería": {
        "name": "Barber Classic",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-slate-50",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-slate-950/90 via-slate-900/75 to-slate-800/50",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "slate-800",
        "primary_bg": "bg-slate-800",
        "primary_text": "text-slate-800",
        "primary_hover": "hover:bg-slate-900",
        "primary_light": "bg-slate-100",
        "primary_light_text": "text-slate-900",
        "accent": "amber-500",
        "accent_bg": "bg-amber-500",
        "accent_text": "text-amber-500",
        "accent_light": "bg-amber-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-amber-400",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-slate-300/30",
        "btn_primary": "bg-gradient-to-r from-slate-800 to-slate-900 hover:from-slate-900 hover:to-black text-white shadow-lg shadow-slate-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-amber-500 hover:text-amber-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-slate-100",
        "icon_text": "text-slate-700",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "spa": {
        "name": "Spa Serenity",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-emerald-50/30",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-emerald-950/90 via-teal-900/70 to-emerald-800/40",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "emerald-600",
        "primary_bg": "bg-emerald-600",
        "primary_text": "text-emerald-600",
        "primary_hover": "hover:bg-emerald-700",
        "primary_light": "bg-emerald-50",
        "primary_light_text": "text-emerald-700",
        "accent": "teal-400",
        "accent_bg": "bg-teal-400",
        "accent_text": "text-teal-500",
        "accent_light": "bg-teal-50",
        "border": "border-gray-100",
        "border_hover": "hover:border-emerald-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-emerald-200/30",
        "btn_primary": "bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white shadow-lg shadow-emerald-500/30",
        "btn_secondary": "bg-white text-gray-700 border-2 border-gray-200 hover:border-emerald-400 hover:text-emerald-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-emerald-100",
        "icon_text": "text-emerald-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-gray-900",
        "footer_text": "text-gray-300",
    },
    
    "belleza": {
        "name": "Beauty Glow",
        "mode": "light",
        "bg_primary": "bg-white",
        "bg_secondary": "bg-pink-50/30",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-pink-950/90 via-rose-900/70 to-pink-800/40",
        "text_primary": "text-gray-900",
        "text_secondary": "text-gray-600",
        "text_muted": "text-gray-500",
        "text_on_primary": "text-white",
        "primary": "pink-500",
        "primary_bg": "bg-pink-500",
        "primary_text": "text-pink-500",
        "primary_hover": "hover:bg-pink-600",
        "primary_light": "bg-pink-50",
        "primary_light_text": "text-pink-600",
        "accent": "rose-400",
        "accent_bg": "bg-rose-400",
        "accent_text": "text-rose-500",
        "accent_light": "bg-rose-50",
        "border": "border-gray-100",
        "border_hover": "hover:border-pink-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-gray-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-pink-200/30",
        "btn_primary": "bg-gradient-to-r from-pink-500 to-rose-500 hover:from-pink-600 hover:to-rose-600 text-white shadow-lg shadow-pink-500/30",
        "btn_secondary": "bg-white text-gray-700 border-2 border-gray-200 hover:border-pink-400 hover:text-pink-500",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-gray-700",
        "navbar_text_scroll": "text-gray-800",
        "icon_bg": "bg-pink-100",
        "icon_text": "text-pink-500",
        "star_color": "text-amber-400",
        "footer_bg": "bg-gray-900",
        "footer_text": "text-gray-300",
    },
    
    # =========================================================================
    # THEME C: INDUSTRIAL / SERVICES (Solid)
    # For: Mechanics, Hardware stores, Gyms, Construction, Services
    # Vibe: Strong, durable, reliable, professional
    # =========================================================================
    
    "industrial": {
        "name": "Industrial Solid",
        "mode": "light",
        "bg_primary": "bg-gray-100",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-slate-950/90 via-slate-900/75 to-indigo-900/50",
        "text_primary": "text-slate-900",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "indigo-700",
        "primary_bg": "bg-indigo-700",
        "primary_text": "text-indigo-700",
        "primary_hover": "hover:bg-indigo-800",
        "primary_light": "bg-indigo-50",
        "primary_light_text": "text-indigo-800",
        "accent": "red-600",
        "accent_bg": "bg-red-600",
        "accent_text": "text-red-600",
        "accent_light": "bg-red-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-indigo-400",
        "divider": "border-gray-200",
        "shadow": "shadow-lg shadow-gray-300/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-indigo-300/30",
        "btn_primary": "bg-gradient-to-r from-indigo-700 to-indigo-800 hover:from-indigo-800 hover:to-indigo-900 text-white shadow-lg shadow-indigo-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-red-500 hover:text-red-600",
        "card_border": "border border-gray-200",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-200",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-indigo-100",
        "icon_text": "text-indigo-700",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "taller": {
        "name": "Auto Workshop",
        "mode": "light",
        "bg_primary": "bg-gray-100",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-blue-950/90 via-slate-900/75 to-blue-900/50",
        "text_primary": "text-slate-900",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "blue-700",
        "primary_bg": "bg-blue-700",
        "primary_text": "text-blue-700",
        "primary_hover": "hover:bg-blue-800",
        "primary_light": "bg-blue-50",
        "primary_light_text": "text-blue-800",
        "accent": "red-600",
        "accent_bg": "bg-red-600",
        "accent_text": "text-red-600",
        "accent_light": "bg-red-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-blue-400",
        "divider": "border-gray-200",
        "shadow": "shadow-lg shadow-gray-300/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-blue-300/30",
        "btn_primary": "bg-gradient-to-r from-blue-700 to-blue-800 hover:from-blue-800 hover:to-blue-900 text-white shadow-lg shadow-blue-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-red-500 hover:text-red-600",
        "card_border": "border border-gray-200",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-200",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-blue-100",
        "icon_text": "text-blue-700",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "mecánico": {
        "name": "Mechanic Pro",
        "mode": "light",
        "bg_primary": "bg-gray-100",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-slate-950/90 via-blue-900/75 to-slate-800/50",
        "text_primary": "text-slate-900",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "slate-700",
        "primary_bg": "bg-slate-700",
        "primary_text": "text-slate-700",
        "primary_hover": "hover:bg-slate-800",
        "primary_light": "bg-slate-100",
        "primary_light_text": "text-slate-800",
        "accent": "orange-500",
        "accent_bg": "bg-orange-500",
        "accent_text": "text-orange-500",
        "accent_light": "bg-orange-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-orange-400",
        "divider": "border-gray-200",
        "shadow": "shadow-lg shadow-gray-300/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-slate-300/30",
        "btn_primary": "bg-gradient-to-r from-slate-700 to-slate-800 hover:from-slate-800 hover:to-slate-900 text-white shadow-lg shadow-slate-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-orange-500 hover:text-orange-600",
        "card_border": "border border-gray-200",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-200",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-slate-200",
        "icon_text": "text-slate-700",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "gimnasio": {
        "name": "Gym Power",
        "mode": "light",
        "bg_primary": "bg-gray-100",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-red-950/90 via-orange-900/75 to-red-900/50",
        "text_primary": "text-slate-900",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "red-600",
        "primary_bg": "bg-red-600",
        "primary_text": "text-red-600",
        "primary_hover": "hover:bg-red-700",
        "primary_light": "bg-red-50",
        "primary_light_text": "text-red-700",
        "accent": "orange-500",
        "accent_bg": "bg-orange-500",
        "accent_text": "text-orange-500",
        "accent_light": "bg-orange-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-red-400",
        "divider": "border-gray-200",
        "shadow": "shadow-lg shadow-gray-300/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-red-300/30",
        "btn_primary": "bg-gradient-to-r from-red-600 to-orange-600 hover:from-red-700 hover:to-orange-700 text-white shadow-lg shadow-red-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-red-500 hover:text-red-600",
        "card_border": "border border-gray-200",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-200",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-red-100",
        "icon_text": "text-red-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "fitness": {
        "name": "Fitness Energy",
        "mode": "light",
        "bg_primary": "bg-gray-100",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-orange-950/90 via-red-900/75 to-orange-900/50",
        "text_primary": "text-slate-900",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "orange-600",
        "primary_bg": "bg-orange-600",
        "primary_text": "text-orange-600",
        "primary_hover": "hover:bg-orange-700",
        "primary_light": "bg-orange-50",
        "primary_light_text": "text-orange-700",
        "accent": "red-500",
        "accent_bg": "bg-red-500",
        "accent_text": "text-red-500",
        "accent_light": "bg-red-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-orange-400",
        "divider": "border-gray-200",
        "shadow": "shadow-lg shadow-gray-300/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-orange-300/30",
        "btn_primary": "bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-700 hover:to-red-700 text-white shadow-lg shadow-orange-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-orange-500 hover:text-orange-600",
        "card_border": "border border-gray-200",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-200",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-orange-100",
        "icon_text": "text-orange-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    "farmacia": {
        "name": "Pharmacy Trust",
        "mode": "light",
        "bg_primary": "bg-slate-50",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-green-950/90 via-emerald-900/70 to-green-800/40",
        "text_primary": "text-slate-800",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "green-600",
        "primary_bg": "bg-green-600",
        "primary_text": "text-green-600",
        "primary_hover": "hover:bg-green-700",
        "primary_light": "bg-green-50",
        "primary_light_text": "text-green-700",
        "accent": "emerald-500",
        "accent_bg": "bg-emerald-500",
        "accent_text": "text-emerald-500",
        "accent_light": "bg-emerald-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-green-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-slate-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-green-200/30",
        "btn_primary": "bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white shadow-lg shadow-green-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-green-500 hover:text-green-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-green-100",
        "icon_text": "text-green-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
    
    # =========================================================================
    # DEFAULT THEME
    # =========================================================================
    
    "default": {
        "name": "Clean Default",
        "mode": "light",
        "bg_primary": "bg-slate-50",
        "bg_secondary": "bg-white",
        "bg_card": "bg-white",
        "bg_hero_overlay": "bg-gradient-to-r from-slate-900/90 via-slate-900/70 to-slate-800/40",
        "text_primary": "text-slate-800",
        "text_secondary": "text-slate-600",
        "text_muted": "text-slate-500",
        "text_on_primary": "text-white",
        "primary": "indigo-600",
        "primary_bg": "bg-indigo-600",
        "primary_text": "text-indigo-600",
        "primary_hover": "hover:bg-indigo-700",
        "primary_light": "bg-indigo-50",
        "primary_light_text": "text-indigo-700",
        "accent": "violet-500",
        "accent_bg": "bg-violet-500",
        "accent_text": "text-violet-500",
        "accent_light": "bg-violet-50",
        "border": "border-gray-200",
        "border_hover": "hover:border-indigo-300",
        "divider": "border-gray-100",
        "shadow": "shadow-lg shadow-slate-200/50",
        "shadow_hover": "hover:shadow-2xl hover:shadow-indigo-200/30",
        "btn_primary": "bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-700 hover:to-violet-700 text-white shadow-lg shadow-indigo-500/30",
        "btn_secondary": "bg-white text-slate-700 border-2 border-slate-200 hover:border-indigo-500 hover:text-indigo-600",
        "card_border": "border border-gray-100",
        "card_hover": "hover:shadow-2xl hover:-translate-y-1",
        "navbar_bg": "bg-white/95 backdrop-blur-md border-b border-gray-100",
        "navbar_text": "text-slate-700",
        "navbar_text_scroll": "text-slate-800",
        "icon_bg": "bg-indigo-100",
        "icon_text": "text-indigo-600",
        "star_color": "text-amber-400",
        "footer_bg": "bg-slate-900",
        "footer_text": "text-slate-300",
    },
}


# =============================================================================
# 🖼️ FALLBACK IMAGES (High-Quality Unsplash)
# =============================================================================

FALLBACK_IMAGES: Dict[str, Dict[str, Any]] = {
    "parrilla": {
        "hero": "https://images.unsplash.com/photo-1544025162-d76694265947?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1558030006-450675393462?w=800&h=600&fit=crop&q=80"]
    },
    "restaurante": {
        "hero": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop&q=80"]
    },
    "café": {
        "hero": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop&q=80"]
    },
    "cafetería": {
        "hero": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop&q=80"]
    },
    "panadería": {
        "hero": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&h=600&fit=crop&q=80"]
    },
    "dentista": {
        "hero": "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800&h=600&fit=crop&q=80"]
    },
    "odontología": {
        "hero": "https://images.unsplash.com/photo-1629909615184-74f495363b67?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=800&h=600&fit=crop&q=80"]
    },
    "clínica": {
        "hero": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&h=600&fit=crop&q=80"]
    },
    "veterinaria": {
        "hero": "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=600&fit=crop&q=80"]
    },
    "peluquería": {
        "hero": "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&h=600&fit=crop&q=80"]
    },
    "barbería": {
        "hero": "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&h=600&fit=crop&q=80"]
    },
    "spa": {
        "hero": "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=600&fit=crop&q=80"]
    },
    "belleza": {
        "hero": "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&h=600&fit=crop&q=80"]
    },
    "gimnasio": {
        "hero": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&h=600&fit=crop&q=80"]
    },
    "fitness": {
        "hero": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=800&h=600&fit=crop&q=80"]
    },
    "taller": {
        "hero": "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&h=600&fit=crop&q=80"]
    },
    "mecánico": {
        "hero": "https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&q=80"]
    },
    "farmacia": {
        "hero": "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1576602976047-174e57a47881?w=800&h=600&fit=crop&q=80"]
    },
    "default": {
        "hero": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&h=1080&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&q=80"]
    },
}


# =============================================================================
# 🎯 SERVICE ICONS (FontAwesome)
# =============================================================================

SERVICE_ICONS: Dict[str, str] = {
    "corte": "fa-scissors",
    "color": "fa-palette",
    "barba": "fa-face-grin-beam",
    "limpieza": "fa-broom",
    "blanqueamiento": "fa-tooth",
    "ortodoncia": "fa-teeth",
    "vacuna": "fa-syringe",
    "consulta": "fa-stethoscope",
    "emergencia": "fa-truck-medical",
    "masaje": "fa-spa",
    "facial": "fa-face-smile",
    "manicure": "fa-hand-sparkles",
    "aceite": "fa-oil-can",
    "frenos": "fa-car",
    "motor": "fa-gear",
    "diagnóstico": "fa-magnifying-glass",
    "asado": "fa-fire",
    "pizza": "fa-pizza-slice",
    "café": "fa-mug-hot",
    "pastel": "fa-cake-candles",
    "fitness": "fa-dumbbell",
    "cardio": "fa-heart-pulse",
    "yoga": "fa-person-praying",
    "default": "fa-star",
}


# =============================================================================
# 📋 CATEGORY FEATURES
# =============================================================================

CATEGORY_FEATURES: Dict[str, list] = {
    "dentista": [
        {"icon": "fa-tooth", "title": "Tecnología Avanzada", "desc": "Equipos de última generación para diagnósticos precisos"},
        {"icon": "fa-shield-halved", "title": "100% Seguro", "desc": "Protocolos de bioseguridad certificados"},
        {"icon": "fa-clock", "title": "Horarios Flexibles", "desc": "Citas que se adaptan a tu agenda"},
        {"icon": "fa-credit-card", "title": "Facilidades de Pago", "desc": "Múltiples opciones de financiamiento"},
    ],
    "veterinaria": [
        {"icon": "fa-heart", "title": "Amor por las Mascotas", "desc": "Tratamos a tu mascota como familia"},
        {"icon": "fa-truck-medical", "title": "Emergencias 24/7", "desc": "Disponibles cuando más nos necesitas"},
        {"icon": "fa-syringe", "title": "Vacunación Completa", "desc": "Programa de vacunación preventiva"},
        {"icon": "fa-user-doctor", "title": "Especialistas", "desc": "Veterinarios con años de experiencia"},
    ],
    "peluquería": [
        {"icon": "fa-scissors", "title": "Estilistas Expertos", "desc": "Profesionales certificados en tendencias"},
        {"icon": "fa-palette", "title": "Color Premium", "desc": "Productos de alta gama para tu cabello"},
        {"icon": "fa-clock", "title": "Sin Esperas", "desc": "Reserva tu turno con anticipación"},
        {"icon": "fa-star", "title": "Ambiente VIP", "desc": "Relájate mientras te embelleces"},
    ],
    "barbería": [
        {"icon": "fa-scissors", "title": "Cortes Clásicos y Modernos", "desc": "Para el caballero moderno"},
        {"icon": "fa-face-grin-beam", "title": "Barba Perfecta", "desc": "Diseño y perfilado profesional"},
        {"icon": "fa-clock", "title": "Puntualidad", "desc": "Respetamos tu tiempo"},
        {"icon": "fa-mug-hot", "title": "Experiencia Completa", "desc": "Café y ambiente exclusivo"},
    ],
    "restaurante": [
        {"icon": "fa-utensils", "title": "Cocina de Autor", "desc": "Platos únicos creados por nuestro chef"},
        {"icon": "fa-leaf", "title": "Ingredientes Frescos", "desc": "Seleccionamos lo mejor cada día"},
        {"icon": "fa-users", "title": "Ambiente Acogedor", "desc": "El lugar perfecto para cada ocasión"},
        {"icon": "fa-calendar-check", "title": "Reservas Online", "desc": "Asegura tu mesa con anticipación"},
    ],
    "taller": [
        {"icon": "fa-magnifying-glass", "title": "Diagnóstico Preciso", "desc": "Identificamos el problema exacto"},
        {"icon": "fa-certificate", "title": "Repuestos Originales", "desc": "Solo usamos piezas de calidad"},
        {"icon": "fa-clock", "title": "Entrega Rápida", "desc": "Tu vehículo listo cuando lo necesitas"},
        {"icon": "fa-shield-halved", "title": "Garantía", "desc": "Respaldamos nuestro trabajo"},
    ],
    "gimnasio": [
        {"icon": "fa-dumbbell", "title": "Equipos de Primera", "desc": "Máquinas modernas y bien mantenidas"},
        {"icon": "fa-users", "title": "Instructores Certificados", "desc": "Te guiamos en cada paso"},
        {"icon": "fa-clock", "title": "Horario Extendido", "desc": "Entrena cuando mejor te convenga"},
        {"icon": "fa-shower", "title": "Instalaciones Premium", "desc": "Vestuarios y duchas impecables"},
    ],
    "default": [
        {"icon": "fa-star", "title": "Calidad Garantizada", "desc": "Nos comprometemos con la excelencia"},
        {"icon": "fa-heart", "title": "Atención Personalizada", "desc": "Cada cliente es especial para nosotros"},
        {"icon": "fa-shield-halved", "title": "Confianza", "desc": "Años de experiencia nos respaldan"},
        {"icon": "fa-clock", "title": "Disponibilidad", "desc": "Estamos cuando nos necesitas"},
    ],
}


# =============================================================================
# 🔧 HELPER FUNCTIONS
# =============================================================================

def get_theme_for_category(category: str) -> Dict[str, Any]:
    """Get the appropriate theme configuration for a business category."""
    if not category:
        return THEMES["default"]
    
    category_lower = category.lower()
    
    # Direct match
    for key in THEMES:
        if key in category_lower:
            return THEMES[key]
    
    # Category group mapping
    category_mappings = {
        ("asado", "carne", "parrillada", "bbq", "grill"): "parrilla",
        ("pizza", "comida", "food", "cocina"): "restaurante",
        ("pub", "cerveza", "drinks", "nightclub", "bar"): "restaurante",
        ("coffee", "cafetería"): "café",
        ("bread", "pan", "bakery", "pastel"): "panadería",
        ("dental", "diente", "tooth", "oral"): "dentista",
        ("médico", "doctor", "hospital", "salud", "health"): "clínica",
        ("mascota", "pet", "animal", "perro", "gato"): "veterinaria",
        ("auto", "car", "motor", "vehículo", "reparación"): "taller",
        ("hair", "cabello", "corte", "salon", "estilista"): "peluquería",
        ("massage", "masaje", "wellness", "relax"): "spa",
        ("barber", "hombre", "men"): "barbería",
        ("gym", "exercise", "crossfit", "yoga"): "gimnasio",
        ("botica", "medicina", "remedios"): "farmacia",
    }
    
    for keywords, theme_key in category_mappings.items():
        if any(kw in category_lower for kw in keywords):
            return THEMES[theme_key]
    
    return THEMES["default"]


def get_fallback_images(category: str) -> Dict[str, Any]:
    """Get fallback images for a business category."""
    if not category:
        return FALLBACK_IMAGES["default"]
    
    category_lower = category.lower()
    
    for key in FALLBACK_IMAGES:
        if key in category_lower:
            return FALLBACK_IMAGES[key]
    
    return FALLBACK_IMAGES["default"]


def get_service_icon(service: str) -> str:
    """Get FontAwesome icon for a service."""
    if not service:
        return SERVICE_ICONS["default"]
    
    service_lower = service.lower()
    
    for key, icon in SERVICE_ICONS.items():
        if key in service_lower:
            return icon
    
    return SERVICE_ICONS["default"]
